version: "3.7"

services:
  base:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    image: etable/php7.0.8
    stdin_open: true
    tty: true

  php708:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_old
    image: etable/php7.0.8-old
    volumes:
      - "./www:/var/www/html"

  nginx:
    image: nginx:alpine
    ports:
      - 7881:7881
    links:
      - "php708:php708"
    volumes:
      - "./www:/var/www/html"
      - "./dist/nginx.conf:/etc/nginx/nginx.conf:ro"
